### PR TITLE
Vsevolod Kaloshin

### PR DESCRIPTION
**Pull request by arzonus**
Hi guys,
I developed the solution. 
Will wait for your feedback :) 

## Technical requirements

1. Application should use gRPC framework for implement messages + server (**DONE**)
2. Should use mongo (**DONE**)
3. Should have cache for get requests (GetByIdRequest,GetByFiltersRequest) + invalidate cache on update (**DONE**)

Additional:
1. Implement github ci for build docker image (**DONE**)
2. Add unit/integration tests (**PARTLY**, only 1 success and 1 fail unit test cases) 
3. Create docker-compose.yml for run it locally (**DONE**)
4. Makefile + linters (**DONE**)

Try to create optimal mongo schema + protobuf schemas

## Non-techincal

1. Provide pull request when work done (**DONE**)

### CODE REVIEW

**Comment by PxyUp** [comment]
@arzonus Hello, will be reviewed soon (this week)

**Comment by PxyUp** [comment]
@arzonus I am quickly check code, but from requirements missing a one thing. GetByFiltersRequest - implementation of this request without caching, as I see. 

PS: CI + Docker part looks super cool

**Comment by arzonus** [comment]
Hello @PxyUp,
Thank you for your response. 
Yeah, you are right. I can add the implementation for the method if it's necessary.

**Comment by PxyUp** [comment]
@arzonus one of idea of this task was check cache for filter query

**Comment by arzonus** [comment]
Ok. I'll add it tomorrow.

**Comment by arzonus** [comment]
Hello @PxyUp
I added caching in `GetByFiltersRequest` :)

**Comment by PxyUp** [comment]
@arzonus Thanks you, will check soon

**Comment by PxyUp** [comment]
@arzonus Hi, i am checked your solution looks good, liked code styled. Solution also works except one situation: because we not control external system we should not caching external status for long time(in your version it is forever). I extend solution with:
```go
&buntdb.SetOptions{
				Expires: true,
				TTL: time.Second * 15,
}
```
But still get old results from cache. It is mean external status not recalculated.

**Comment by arzonus** [comment]
Hello @PxyUp,
Thank you for your feedback. 

Unfortunately, I haven't read carefully (my bad) about dependency between an application and the external system in the task description. So, I decided that external status will be permanent for an application, so we can save it to the db. Otherwise, we shouldn't store external status in the db and we need to cache it after getting from the external system.

So, the app has wrong logic and I agree with that. Sure, I can fix it, but it will take time. Maybe we could proceed without it for speeding up the hiring process because it is taking more than 1 month?

**Comment by PxyUp** [comment]
@arzonus yes, I already provide feedback to HR during this morning

**Comment by arzonus** [comment]
@PxyUp thank you 👍

**Pull request closed without merging**
